//generated by generate_images.py

const eye_colours = ["#000000","#AEB655","#14AC34","#20514C","#29B4C4","#008891","#2E9FF7","#3D2C64","#B200F1","#F39EFF","#FE023A","#D24525","#FF8F2B","#DB8200","#8E3300","#999999","#ffffff",];
const outfit_colours = ["#F8EABC","#FFE201","#FFCC98","#F7BE4F","#FF9F02","#73D080","#8CC54E","#56AA04","#277032","#4F8B20","#7CA838","#8C8A2D","#A6E7CD","#008186","#477BC8","#3C92ED","#1FDBFF","#2E4D91","#A46FE2","#9431C6","#BF2C92","#D361A7","#A01B54","#FF8B91","#E55773","#F0303C","#B71B00","#B24836","#8E4A17","#912D20","#820000","#630F0F","#FFFFFF","#A8ADAE","#777471","#4C4C56","#482B57","#000000",];
const skin_colours = ["#FFE7D6","#FFECD6","#FFD3A6","#FFDFA5","#F1A065","#F1B265","#DA773F","#DA874A","#B05934","#B96A2E","#853F27","#783F1A",];
const hair_colours = ["#FCE374","#F0B50A","#FE7423","#FF5565","#DF433C","#D16132","#641D00","#923D1F","#8B4910","#BB742E","#A59A9D","#E9E9E9","#391E47","#48356E","#4B261E","#5B483C","#5A5A7F","#602372","#000000",];

const no_lines_list = ["iris","cheeks",];
const no_fill_list = ["mouth","eye_shape",];
const no_iris_list = ["sleepy","closed",];
const pattern_list = ["none","crocodile","rose","snake","damask","crosshatch","fabric","diamonds","diamondssmall","tartan","polkadot","pinstripe","horizontalpinstripe",];
const skin_list = ["body","head","nose","mouth","eyebrows","eye_shape",];
const outfit_list = ["wheelchair_front","bottom","top","accessory","face_dec","gloves","hat","coat",];
const defining_list = ["wheelchair_front","bottom","top","accessory","face_dec","gloves","hat","coat","body","head","nose","mouth","eyebrows","eye_shape","hair_front","iris","cheeks",];

const coat_back_list_d = [["none","mediumcloak","wrap",],["none","mediumcloak","wrap",],];
const hat_back_list_d = [["none","tophat","scarf","turban",],["none","tophat","scarf","turban",],];
const hair_back_list_d = [["supershort","curlylong","centrebun","wavybun","straightbun","curlyshort","flowing","curlybun","straightshort","wavyshort",],["supershort","curlylong","centrebun","wavybun","straightbun","curlyshort","flowing","curlybun","straightshort","wavyshort",],];
const body_list_d = [["regular","regular",],["regular","regular",],];
const cheeks_list_d = [["none","blush",],["none","blush",],];
const gloves_list_d = [["none","shortgloves","mediumgloves","longgloves","bracelets",],["none","shortgloves",],];
const top_list_d = [["bodiceplain","bodicelong","bodicefancy","bodicepointy",],["shirtopen","shirtclosed","shirtcravat",],];
const bottom_list_d = [["plainskirt","fancyskirt","lowskirt",],["breeches","trousers",],];
const accessory_list_d = [["none","pendant","choker","fancychoker","beads",],["none","waistcoat",],];
const coat_list_d = [["none","mediumcloak","dressjacket","wrap",],["none","shortjacket","longjacketclosed","jama",],];
const chest_list_d = [["none","smooth","curvy",],["none",],];
const top_collar_list_d = [["none",],["shirtopen","shirtclosed","shirtcravat",],];
const head_list_d = [["pointy","regular","chin","round",],["pointy","regular","chin","round",],];
const nose_list_d = [["button","round","medium","broad","pointy","pointy2",],["button","round","medium","broad","pointy","pointy2",],];
const mouth_list_d = [["grintall","grin","grinside","grinsmall","lah","lahsmall","lahtiny","smileside","smilebig","smilebigside","smilewideflat","p","sleaze","smileflat","smile","smilesmall","smiletiny","obig","o","osquare","osmall","dbig","d","dsmall","eww","ewwobble","nng","flatsmall","flat","t","tlow","wibble","frowntiny","frownsmall","frownnarrow","frown","pout","frownside","frownbig","frownopen",],["grintall","grin","grinside","grinsmall","lah","lahsmall","lahtiny","smileside","smilebig","smilebigside","smilewideflat","p","sleaze","smileflat","smile","smilesmall","smiletiny","obig","o","osquare","osmall","dbig","d","dsmall","eww","ewwobble","nng","flatsmall","flat","t","tlow","wibble","frowntiny","frownsmall","frownnarrow","frown","pout","frownside","frownbig","frownopen",],];
const eyebrows_list_d = [["flat","flatsad","flatgrumpy","flatangry","sad","sadder","sadsemi","regular","archsemi","arched","archraised","raised","raisedflat","raisedsemiflat","raisedgrumpy","raisedsemi","angry","angryarch","halfraised","halfsemi","halfsad","halfsadraised","halfflat","halfarchraised",],["flat","flatsad","flatgrumpy","flatangry","sad","sadder","sadsemi","regular","archsemi","arched","archraised","raised","raisedflat","raisedsemiflat","raisedgrumpy","raisedsemi","angry","angryarch","halfraised","halfsemi","halfsad","halfsadraised","halfflat","halfarchraised",],];
const iris_list_d = [["wide","extrawide","widecatty","sad","gentle","regular","vivid","cool","catty","coolside","narrowcool","narrowcoolside","narrowcatty","narrowcattyside","halfclosed",],["wide","extrawide","widecatty","sad","gentle","regular","vivid","cool","catty","coolside","narrowcool","narrowcoolside","narrowcatty","narrowcattyside","halfclosed",],];
const eye_shape_list_d = [["wide","extrawide","widecatty","sad","gentle","regular","vivid","cool","catty","coolside","narrowcool","narrowcoolside","narrowcatty","narrowcattyside","halfclosed","sleepy","closed",],["wide","extrawide","widecatty","sad","gentle","regular","vivid","cool","catty","coolside","narrowcool","narrowcoolside","narrowcatty","narrowcattyside","halfclosed","sleepy","closed",],];
const face_dec_list_d = [["none","roundglasses","dropearrings","stud","roundearrings",],["none","roundglasses","beard",],];
const hair_front_list_d = [["centrebun","curlybun","wavybun","straightbun","curlylong","flowing",],["centrebun","curlyshort","wavyshort","straightshort","supershort",],];
const hat_list_d = [["none","beads",],["none","tophat","turban",],];
const wheelchair_list_d = [["none","regular",],["none","regular",],];
const wheelchair_coat_list_d = [["none","mediumcloak","longjacketclosed","dressjacket","jama",],["none","mediumcloak","longjacketclosed","dressjacket","jama",],];

add_image_object("wheelchair_back",wheelchair_list_d,"wheelchair")
add_image_object("coat_back",coat_back_list_d,"clothes/coat")
add_image_object("hat_back",hat_back_list_d,"clothes/hat")
add_image_object("hair_back",hair_back_list_d,"hair")
add_image_object("body",body_list_d,"anatomy")
add_defining_object("body",body_list_d)
add_image_object("cheeks",cheeks_list_d,"face")
add_defining_object("cheeks",cheeks_list_d)
add_image_object("gloves",gloves_list_d,"clothes")
add_defining_object("gloves",gloves_list_d)
add_image_object("top",top_list_d,"clothes")
add_defining_object("top",top_list_d)
add_image_object("bottom",bottom_list_d,"clothes")
add_defining_object("bottom",bottom_list_d)
add_image_object("accessory",accessory_list_d,"clothes")
add_defining_object("accessory",accessory_list_d)
add_image_object("coat",coat_list_d,"clothes")
add_defining_object("coat",coat_list_d)
add_image_object("chest",chest_list_d,"anatomy")
add_image_object("top_collar",top_collar_list_d,"clothes")
add_image_object("head",head_list_d,"anatomy")
add_defining_object("head",head_list_d)
add_image_object("nose",nose_list_d,"face")
add_defining_object("nose",nose_list_d)
add_image_object("mouth",mouth_list_d,"face")
add_defining_object("mouth",mouth_list_d)
add_image_object("eyebrows",eyebrows_list_d,"face")
add_defining_object("eyebrows",eyebrows_list_d)
add_image_object("iris",iris_list_d,"face/eyes")
add_defining_object("iris",iris_list_d)
add_image_object("eye_shape",eye_shape_list_d,"face/eyes")
add_defining_object("eye_shape",eye_shape_list_d)
add_image_object("face_dec",face_dec_list_d,"clothes")
add_defining_object("face_dec",face_dec_list_d)
add_image_object("hair_front",hair_front_list_d,"hair")
add_defining_object("hair_front",hair_front_list_d)
add_image_object("hat",hat_list_d,"clothes")
add_defining_object("hat",hat_list_d)
add_image_object("wheelchair_front",wheelchair_list_d,"wheelchair")
add_defining_object("wheelchair_front",wheelchair_list_d)
add_image_object("wheelchair_coat",wheelchair_coat_list_d,"wheelchair")

