//generated by generate_images.py

const eye_colours = ["#000000","#8334D8","#AD4C1F","#FFB02B","#D48A0B","#954213","#7F8723","#38AE2A","#146C24","#1ABACB","#83DFDF","#1E8990","#4C9EE8","#274CA4","#878E9E","#663D49",];
const outfit_colours = ["#FAF6E9","#FAF1CF","#FAE181","#91C639","#43A92D","#1B7C34","#5B8DDD","#4C6BC2","#9CD6F8","#C089E4","#7543BD","#28137C","#E3313C","#901E3B","#E1748A",];
const outfit_brown = ["#F6AC4F","#DA711F","#C49052","#A76C42","#83402C","#462231",];
const skin_colours = ["#FFE5C9","#FFE5C9","#FFE5C9","#F8C38D","#F1A065","#F3AE74","#EA8C59","#C26638","#CA783C","#8D4428","#A85E29","#6F3226","#723C1B",];
const hair_colours = ["#D88F3F","#F5D06D","#D19546","#D14728","#D15E23","#712A0D","#A44C17","#8A3C25","#9E8F7E","#C6C2BE","#471E27","#612230","#9C7256",];

const no_render_list = [["hat",["scarf",]],["hat_dec",["scarf",]],];
const no_fill_list = ["mouth",];
const eyetype_list = ["medium",];
const pattern_list = ["none","crocodile","rose","snake","damask","crosshatch","fabric","diamonds","diamondssmall","tartan","polkadot","pinstripe","horizontalpinstripe",];
const skin_list = ["body","nose","mouth","eyebrows","skull","complexion","ears",];
const chest_image_list = ["none","smooth","curvy","curvypants","smoothwide","curvywide",];
const no_chest_coat_list = ["robe","robe hood","medium cloak","medium cloak hood","long cloak","long cloak hood","wrap",];
const expression_list = ["mouth","eyebrows","cheeks","eyes",];
const outfit_list = ["wheelchair","bottom","top","overshirt","coat",];
const accessory_list = ["eyewear","neckwear","earrings","gloves","hat",];
const defining_list = ["eyebrows","neckwear","head","bottom","top","eyewear","chest","complexion","earrings","hat","cheeks","body","eyes","mouth","hair_front","skull","coat","wheelchair","overshirt","gloves","nose","ears",];

const hat_back_list_d = [["none","top hat","scarf","turban",],["none","top hat","scarf","turban",],];
const hat_back_dec_list_d = [["scarf",],["scarf",],];
const hair_back_list_d = [["none","straight bun","curly bun","wavy bun","super short","curly short","straight short","wavy short","centre bun","straight long","curly long",],["none","straight bun","curly bun","wavy bun","super short","curly short","straight short","wavy short","centre bun","straight long","curly long",],];
const coat_back_list_d = [["none","medium cloak","wrap","long jacket closed","short jacket","dress jacket",],["none","medium cloak","wrap","long jacket closed","short jacket","dress jacket",],];
const body_list_d = [["regular",],["regular",],];
const gloves_list_d = [["none","short gloves","medium gloves","long gloves","bracelets",],["none","short gloves",],];
const top_list_d = [["none","plain bodice","long sleeve bodice","gathered bodice","v neck bodice",],["none","open shirt","closed shirt",],];
const top_dec_list_d = [["plain bodice","long sleeve bodice","gathered bodice","v neck bodice",],["plain bodice","long sleeve bodice","gathered bodice","v neck bodice",],];
const bottom_list_d = [["none","solid skirt","split skirt","low skirt",],["none","breeches","trousers",],];
const bottom_dec_list_d = [["breeches","split skirt","solid skirt",],["breeches","split skirt","solid skirt",],];
const neckwear_list_d = [["none","beaded necklace","choker","jewelled necklace","beads",],["none","cravat","bow",],];
const neckwear_dec_list_d = [["jewelled necklace","beaded necklace",],["jewelled necklace","beaded necklace",],];
const overshirt_list_d = [["none",],["none","waistcoat",],];
const overshirt_dec_list_d = [["waistcoat","short waistcoat",],["waistcoat","short waistcoat",],];
const top_collar_list_d = [["none",],["none","open shirt","closed shirt",],];
const coat_list_d = [["none","medium cloak","dress jacket","wrap",],["none","short jacket","long jacket closed","jama",],];
const coat_dec_list_d = [["dress jacket","jama",],["dress jacket","jama",],];
const chest_list_d = [["none","smooth","curvy",],["none",],];
const skull_list_d = [["regular",],["regular",],];
const head_list_d = [["pointed","medium","rectangular","round",],["pointed","medium","rectangular","round",],];
const ear_list_d = [["regular",],["regular",],];
const earrings_list_d = [["none","drop earrings","stud","round earrings",],["none",],];
const earrings_dec_list_d = [["round earrings",],["round earrings",],];
const nose_list_d = [["button","round","medium","broad","pointed","hooked",],["button","round","medium","broad","pointed","hooked",],];
const complexion_list_d = [["none","slight lines","freckles",],["none","slight lines","freckles",],];
const cheeks_list_d = [["none","blush",],["none","blush",],];
const mouth_list_d = [["lah","small lah","tiny lah","big grin","grin","side grin","side smile","big smile","big side smile","wide flat smile","tongue out","flat smile","smile","small smile","tiny smile","slight smile","side eww","eww","oh","square oh","big oh","small oh","shock","small flat","flat","small clenched","wobbly frown","tiny frown","small frown","narrow frown","frown","low moue","moue","pout","side frown","big frown",],["lah","small lah","tiny lah","big grin","grin","side grin","side smile","big smile","big side smile","wide flat smile","tongue out","flat smile","smile","small smile","tiny smile","slight smile","side eww","eww","oh","square oh","big oh","small oh","shock","small flat","flat","small clenched","wobbly frown","tiny frown","small frown","narrow frown","frown","low moue","moue","pout","side frown","big frown",],];
const eyebrows_list_d = [["flat","flat sad","flat grumpy","flat angry","sad","sadder","semi sad","regular","semi arch","arched","raised arch","raised","raised flat","raised semi flat","raised grumpy","raised semi","angry","angry arch","half raised","half semi","half sad","half sad raised","half flat","half arch raised",],["flat","flat sad","flat grumpy","flat angry","sad","sadder","semi sad","regular","semi arch","arched","raised arch","raised","raised flat","raised semi flat","raised grumpy","raised semi","angry","angry arch","half raised","half semi","half sad","half sad raised","half flat","half arch raised",],];
const eyes_list_d = [["neutral","side","crescents","narrowed","happy","wide","shock","angry","angry side","sleepy","wink",],["neutral","side","crescents","narrowed","happy","wide","shock","angry","angry side","sleepy","wink",],];
const eyewear_list_d = [["none","round glasses",],["none","round glasses","monocle",],];
const hair_front_list_d = [["none","centre bun","curly bun","wavy bun","straight bun","curly long","straight long",],["none","centre bun","curly short","wavy short","straight short","super short",],];
const hat_list_d = [["none","beads","scarf",],["none","top hat","turban",],];
const hat_dec_list_d = [["top hat",],["top hat",],];
const wheelchair_list_d = [["none","regular",],["none","regular",],];
const wheelchair_bottom_list_d = [["none","solid skirt","split skirt","low skirt",],["none","breeches","trousers",],];
const wheelchair_bottom_dec_list_d = [["breeches","split skirt",],["breeches","split skirt",],];
const wheelchair_coat_list_d = [["none","medium cloak","long jacket closed","dress jacket","jama",],["none","medium cloak","long jacket closed","dress jacket","jama",],];

add_image_object("wheelchair_back",wheelchair_list_d,"wheelchair")
add_image_object("wheelchair_back_dec",wheelchair_list_d,"wheelchair")
add_image_object("hat_back",hat_back_list_d,"clothes/hat")
add_image_object("hat_back_dec",hat_back_dec_list_d,"clothes/hat")
add_image_object("hair_back",hair_back_list_d,"hair")
add_image_object("coat_back",coat_back_list_d,"clothes/coat")
add_image_object("body",body_list_d,"anatomy")
add_defining_object("body",body_list_d)
add_image_object("gloves",gloves_list_d,"clothes")
add_defining_object("gloves",gloves_list_d)
add_image_object("top",top_list_d,"clothes")
add_defining_object("top",top_list_d)
add_image_object("top_dec",top_dec_list_d,"clothes")
add_image_object("bottom",bottom_list_d,"clothes")
add_defining_object("bottom",bottom_list_d)
add_image_object("bottom_dec",bottom_dec_list_d,"clothes")
add_image_object("neckwear",neckwear_list_d,"clothes")
add_defining_object("neckwear",neckwear_list_d)
add_image_object("neckwear_dec",neckwear_dec_list_d,"clothes")
add_image_object("overshirt",overshirt_list_d,"clothes")
add_defining_object("overshirt",overshirt_list_d)
add_image_object("overshirt_dec",overshirt_dec_list_d,"clothes")
add_image_object("top_collar",top_collar_list_d,"clothes")
add_image_object("coat",coat_list_d,"clothes")
add_defining_object("coat",coat_list_d)
add_image_object("coat_dec",coat_dec_list_d,"clothes")
add_image_object("chest",chest_list_d,"anatomy")
add_defining_object("chest",chest_list_d)
add_image_object("skull",skull_list_d,"anatomy")
add_defining_object("skull",skull_list_d)
add_image_object("head",head_list_d,"anatomy")
add_defining_object("head",head_list_d)
add_image_object("ears",ear_list_d,"anatomy")
add_defining_object("ears",ear_list_d)
add_image_object("earrings",earrings_list_d,"clothes")
add_defining_object("earrings",earrings_list_d)
add_image_object("earrings_dec",earrings_dec_list_d,"clothes")
add_image_object("nose",nose_list_d,"face")
add_defining_object("nose",nose_list_d)
add_image_object("complexion",complexion_list_d,"face")
add_defining_object("complexion",complexion_list_d)
add_image_object("cheeks",cheeks_list_d,"face")
add_defining_object("cheeks",cheeks_list_d)
add_image_object("mouth",mouth_list_d,"face")
add_defining_object("mouth",mouth_list_d)
add_image_object("eyebrows",eyebrows_list_d,"face")
add_defining_object("eyebrows",eyebrows_list_d)
add_image_object("eyes",eyes_list_d,"face")
add_defining_object("eyes",eyes_list_d)
add_image_object("eyewear",eyewear_list_d,"clothes")
add_defining_object("eyewear",eyewear_list_d)
add_image_object("hair_front",hair_front_list_d,"hair")
add_defining_object("hair_front",hair_front_list_d)
add_image_object("hat",hat_list_d,"clothes")
add_defining_object("hat",hat_list_d)
add_image_object("hat_dec",hat_dec_list_d,"clothes")
add_image_object("wheelchair",wheelchair_list_d,"wheelchair")
add_defining_object("wheelchair",wheelchair_list_d)
add_image_object("wheelchair_dec",wheelchair_list_d,"wheelchair")
add_image_object("wheelchair_bottom",wheelchair_bottom_list_d,"wheelchair")
add_image_object("wheelchair_bottom_dec",wheelchair_bottom_dec_list_d,"wheelchair")
add_image_object("wheelchair_coat",wheelchair_coat_list_d,"wheelchair")

